Create interface for accessing the training code
instructlab/training pull request #12
Opened 2024-06-11 18:38 UTC by RobotSail

This PR turns this into a library.

2024-06-11 19:21 UTC, russellb requested changes

2024-06-11 19:21 UTC, russellb commented on setup.py
> +import os
Instead of setup.py, can you create a pyproject.toml similar to the `instructlab` and `sdg` repos?

The `sdg` one is probably a better one to copy, since it's a library similar to this one.

2024-06-11 19:21 UTC, russellb commented on ilab_train/config.py
> +from dataclasses import dataclass
To be consistent with other libraries, can you set this up as `instructlab.train` as the library?

See this PR for some guidance on what to change to do this:

https://github.com/instructlab/sdg/pull/14

2024-06-11 19:39 UTC, RobotSail commented on setup.py
> +import os
Sure, I'm not married to `setup.py` and find it to be clunky. Seems like pyproject.toml is a better solution.

2024-06-11 19:39 UTC, RobotSail commented on ilab_train/config.py
> +from dataclasses import dataclass
Sure, I like that more.

2024-06-12 13:43 UTC, nathan-weinberg commented on setup.py
> +import os
I copied the `sdg` config for https://github.com/instructlab/eval - all three libs should work the same and remain in sync

2024-06-12 13:43 UTC, nathan-weinberg commented on ilab_train/config.py
> +from dataclasses import dataclass
@RobotSail you can also reference https://github.com/instructlab/eval/pull/1

2024-06-12 17:36 UTC, RobotSail commented
https://github.com/instructlab/eval/pull/1

2024-06-13 14:52 UTC, russellb reviewed
I haven't reviewed the code part, just pyproject/requirements/namespace package portions. That all looks good, though I gave some suggested edits for some minor cleanup. That includes dropping Python 3.9 since I think we landed on 3.10 as the minimum.

2024-06-13 14:52 UTC, russellb commented on pyproject.toml
> +    "Programming Language :: Python :: 3.12",
```suggestion
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
```

2024-06-13 14:52 UTC, russellb commented on pyproject.toml
> +target-version = "py39"
```suggestion
target-version = "py310"
```
```

2024-06-13 14:52 UTC, russellb commented on pyproject.toml
> +"instructlab.schema.v2" = ["*.json"]
```suggestion
```

2024-06-13 14:52 UTC, russellb commented on pyproject.toml
> +homepage = "https://instructlab.io"
```suggestion
homepage = "https://instructlab.ai"
```

2024-06-13 14:52 UTC, russellb commented on requirements.txt
> +deepspeed
Not for this PR, but later this should get updated to add some more specific versions for each line.

Take a look at requirements.txt in the `instructlab/instructlab` repo for some examples where we put guardrails around minimum/maximum for each

2024-06-13 14:56 UTC, nathan-weinberg requested changes
Just focused on the Python packaging stuff, will leave the training code itself to y'all for now :smile:

2024-06-13 14:56 UTC, nathan-weinberg commented on pyproject.toml
> +requires-python = ">=3.9"
```suggestion
requires-python = ">=3.10"
```

2024-06-13 14:56 UTC, nathan-weinberg commented on requirements.txt
> +deepspeed
+1 to this, also the empty line L9 should be removed

@mairin has highlighted that torch 2.2.0 has a CVE, so can we bump that to 2.3.0?

2024-06-13 15:14 UTC, russellb commented on requirements.txt
> +deepspeed
This actually raises an important point of pain we're going to hit immediately by splitting up into these separate repos.

All of these requirements.txt files have to be compatible. We'll need a process for dealing with any and all requirements changes to ensure it's done consistently across repos to ensure they remain compatible.

2024-06-13 16:35 UTC, RobotSail commented on requirements.txt
> +deepspeed
I agree, we should add the specific requirements down the line. They probably shouldn't be added in this PR yet while we're still sorting things out.

As for the empty line, we need deepspeed to be the very last entry since it depends on the ones above and breaks if it's included anywhere other than here.
I'll add a comment to explain this.

2024-06-13 16:40 UTC, RobotSail commented on pyproject.toml
> +    "Programming Language :: Python :: 3.12",
Thanks for this suggestion!

2024-06-13 16:41 UTC, RobotSail commented on pyproject.toml
> +target-version = "py39"
Thanks!

2024-06-13 16:41 UTC, RobotSail commented on pyproject.toml
> +requires-python = ">=3.9"
Good catch, thanks!

2024-06-13 16:54 UTC, RobotSail commented on src/instructlab/training/main_ds.py
> +            f"--data_path={train_args.data_path}",
Mustafa: this should be the processed data path

2024-06-13 16:56 UTC, RobotSail commented on src/instructlab/training/main_ds.py
> +            f"--seed={train_args.seed}",
Mustafa: needs to add the new args for lora & quantization

2024-06-13 16:58 UTC, RobotSail commented on src/instructlab/training/main_ds.py
> +        # stream the stdout and stderr output
need to implement this

2024-06-14 17:15 UTC, Maxusmusti commented
Note: Current requirements will overwrite existing nvidia pytorch installs. Need to ensure that if those exist, we are not installing our own torch.

2024-06-14 17:28 UTC, Maxusmusti commented on src/instructlab/training/main_ds.py
> +def run_training(torch_args: TorchrunTrainArgs, train_args: FullTrainArgs):
Update names of imports

2024-06-14 17:36 UTC, Maxusmusti commented on src/instructlab/training/config.py
> +    processed_data_output_path: str
Change to directory, name doesn't matter

2024-06-14 17:36 UTC, Maxusmusti commented on src/instructlab/training/config.py
> +    num_gpus: int
to be removed (already in torchrun args)

2024-06-14 17:47 UTC, Maxusmusti commented on src/instructlab/training/main_ds.py
> +    if not os.path.exists(train_args.output_dir):
Change to ckpt_output_dir

2024-06-14 17:47 UTC, Maxusmusti commented on src/instructlab/training/main_ds.py
> +            f"--output_dir={train_args.output_dir}",
fix here too

2024-06-14 17:48 UTC, Maxusmusti commented on src/instructlab/training/main_ds.py
> +    if not os.path.exists(train_args.output_dir):
*path

2024-06-14 17:49 UTC, Maxusmusti commented on src/instructlab/training/main_ds.py
> +            f"--model_name_or_path={train_args.model_name_or_path}",
change to just model_path

2024-06-14 17:50 UTC, Maxusmusti commented on src/instructlab/training/main_ds.py
> +            f"--num_warmup_steps={train_args.num_warmup_steps}",
change to just warmup_steps

2024-06-14 17:51 UTC, Maxusmusti commented on src/instructlab/training/main_ds.py
> +            f"--log_level={train_args.log_level}",
change to just "INFO"

2024-06-14 17:52 UTC, Maxusmusti commented on src/instructlab/training/config.py
> +
add seed as option

2024-06-14 17:53 UTC, Maxusmusti commented on src/instructlab/training/config.py
> +    ds_offload_strat: DeepSpeedOffloadStrategy
add mock_data as option

2024-06-14 17:58 UTC, Maxusmusti commented on src/instructlab/training/config.py
> +    warmup_steps: int
add is_granite (but maybe as is_padding_free)

2024-06-14 18:00 UTC, Maxusmusti commented on src/instructlab/training/main_ds.py
> +            f"--data_path={train_args.processed_data_output_path}",
expected hera as file, but in process_data as a dir

2024-06-17 15:54 UTC, JamesKunstle requested changes
two thoughts, one being a minor nit-pick, but in general this is very good, I'll check that it runs.

2024-06-17 15:54 UTC, JamesKunstle commented on README.md
> +    rdzv_endpoint = '127.0.0.1:12345'
very minor nit- the second machine wouldn't refer to localhost, it'd refer to the public IP of the main machine.

2024-06-17 15:54 UTC, JamesKunstle commented on src/instructlab/training/config.py
> +
should there be an 8-bit quanitzation size that's supported?

2024-06-17 15:57 UTC, Maxusmusti commented on src/instructlab/training/config.py
> +
Not yet, we can experiment with and include that in a follow-up once we've got some validation for it (if we have time). For now our code only has 4-bit support, so makes sense for interface to match.

2024-06-17 15:58 UTC, RobotSail commented on src/instructlab/training/config.py
> +
Yes but the LoRA training which Fabian implemented only supports 4-bit quantization. Since this PR is only concerned with the interface, we should leave this for a follow-up PR.

Made an issue for it here:
https://github.com/instructlab/training/issues/29

2024-06-17 15:59 UTC, RobotSail commented on README.md
> +    rdzv_endpoint = '127.0.0.1:12345'
Good catch!

2024-06-17 16:02 UTC, RobotSail commented on README.md
> +    rdzv_endpoint = '127.0.0.1:12345'
Updated

2024-06-17 16:04 UTC, RobotSail commented
Thank you for the review @JamesKunstle, I've created an issue about your quantization comment here: https://github.com/instructlab/training/issues/29

2024-06-17 17:26 UTC, cdoern commented on src/instructlab/training/config.py
> +class TrainingArgs(BaseModel):
PTAL at instructlab/instructlab#1370

2024-06-17 17:35 UTC, cdoern reviewed
initial comments. Want to make sure this is aligned with CLI impl.

2024-06-17 17:35 UTC, cdoern commented on src/instructlab/training/main_ds.py
> +def get_ds_config(world_size, samples_per_gpu, grad_accum, opts: DeepSpeedOptions):
ok, I have been operating under the assumption that the Ds config would live in the cli. What if eventually we want to allow ppl to give their own ds config?

2024-06-17 17:35 UTC, cdoern commented on src/instructlab/training/main_ds.py
> +
two blank lines

2024-06-17 17:35 UTC, cdoern commented on src/instructlab/training/main_ds.py
> +def run_training(torch_args: TorchrunArgs, train_args: TrainingArgs):
so, is the cli meant to call this? In terms of passing the args would it be possible to have torch and train args as one object? otherwise if we ever let the user customize this, would they have to understand the difference btwn the two?

2024-06-17 17:35 UTC, cdoern commented on src/instructlab/training/main_ds.py
> +def run_training(torch_args: TorchrunArgs, train_args: TrainingArgs):
also,  I may just be missing this, but where is the preserved CLI linux train code?

2024-06-17 17:39 UTC, RobotSail commented on src/instructlab/training/main_ds.py
> +def get_ds_config(world_size, samples_per_gpu, grad_accum, opts: DeepSpeedOptions):
We still need you to pass the DeepSpeedConfig, you would just be doing it via the `deepspeed` field in `TrainingArgs`. the `get_ds_config` option just builds the actual config that deepspeed itself consumes. 

The reason we're doing it this way is to limit the surface of what we enable with DeepSpeed.

2024-06-17 17:40 UTC, RobotSail commented on src/instructlab/training/main_ds.py
> +def run_training(torch_args: TorchrunArgs, train_args: TrainingArgs):
Yes the CLI will be calling this. 

> also, I may just be missing this, but where is the preserved CLI linux train code?

We haven't moved over the existing CLI train code and instead added a LoRA implementation that @fabianlim provided us.

2024-06-17 17:41 UTC, RobotSail commented on src/instructlab/training/main_ds.py
> +
Formatter made this change.

2024-06-17 17:41 UTC, JamesKunstle commented on src/instructlab/training/config.py
> +
++ sounds great.

2024-06-17 17:42 UTC, Maxusmusti commented on src/instructlab/training/main_ds.py
> +def run_training(torch_args: TorchrunArgs, train_args: TrainingArgs):
the training library has full feature parity with the old linux train code, lora/qlora supported

2024-06-17 17:47 UTC, cdoern approved these changes

2024-06-17 17:49 UTC, russellb requested changes
Can you squash the commit history here before merging?

2024-06-17 17:51 UTC, JamesKunstle approved these changes
v good thank you for all your work

2024-06-17 17:54 UTC, nathan-weinberg approved these changes

2024-06-17 17:57 UTC, russellb requested changes
biggestion question here is about the use of class variables.

In terms of PR structure -- it would have been nice to have the PR that's doing the library setup setup from all the API introduction stuff.

2024-06-17 17:57 UTC, russellb commented on README.md
> +namely:
Minor suggestion:

```suggestion
To use the library, import the necessary items:
```

2024-06-17 17:57 UTC, russellb commented on README.md
> +via `torchrun`. To do this, simply create a `TorchrunArgs` object.
Minor suggestion:

```suggestion
via `torchrun`. To do this, create a `TorchrunArgs` object.
```

2024-06-17 17:57 UTC, russellb commented on requirements.txt
> +deepspeed==0.14.3
Can you file a follow-up issue about restricting the versions and ensuring they're compatible with `instructlab/instructlab` ?

2024-06-17 17:57 UTC, russellb commented on src/instructlab/training/config.py
> +    model_config = ConfigDict(protected_namespaces=())
These are all class variables, right?

I would think having one instance of every one of these for all instances of the class isn't really what you want? This applies to most of the classes after this one.

2024-06-17 17:58 UTC, Maxusmusti approved these changes
LGTM, tested full training (no lora/offload) with both base scripts and updated interface, both functioning as expected

2024-06-17 18:09 UTC, RobotSail commented on README.md
> +namely:
I love it

2024-06-17 18:09 UTC, RobotSail commented on README.md
> +via `torchrun`. To do this, simply create a `TorchrunArgs` object.
👨‍🍳 🤌

2024-06-17 18:09 UTC, RobotSail commented on requirements.txt
> +deepspeed==0.14.3
In this repo or the CLI one?

2024-06-17 18:11 UTC, RobotSail commented on src/instructlab/training/config.py
> +    model_config = ConfigDict(protected_namespaces=())
No, see the docs for Pydantic (and dataclasses):
https://docs.pydantic.dev/latest/

It lets you create type-safe structs, but you declare the variables at the class-level. It's unusual, but it works.

2024-06-17 18:54 UTC, russellb commented on requirements.txt
> +deepspeed==0.14.3
this one

2024-06-17 19:00 UTC, russellb commented on src/instructlab/training/config.py
> +    model_config = ConfigDict(protected_namespaces=())
Thanks for clarifying!

2024-06-17 19:03 UTC, russellb commented on setup.py
> +import os
looks like you can drop this commit, right?  or squash it

2024-06-17 19:03 UTC, russellb commented on .gitignore
> +# Attribution:
You can squash this into the first commit.

When do you do so, can you update the commit message so it's a single message that describes the sum of what's included?

2024-06-17 19:12 UTC, russellb commented
just to be super clear:

1. squash the first two commits and fix up the commit message
2. create a follow-up issue for cleaning up requirements.txt to specify versions for all dependencies + making sure the versions are aligned with `instructlab/instructlab` if it's a shared dependency

2024-06-17 19:29 UTC, RobotSail commented on setup.py
> +import os
oh right we can just drop this

2024-06-17 19:30 UTC, RobotSail commented on .gitignore
> +# Attribution:
Yep

2024-06-17 19:33 UTC, merged

2024-06-17 20:35 UTC, russellb commented
> 2. create a follow-up issue for cleaning up requirements.txt to specify versions for all dependencies + making sure the versions are aligned with `instructlab/instructlab` if it's a shared dependency

We talked about this, so I know your intent was to create this issue, but I can't find it anywhere. I went ahead and filed this one: https://github.com/instructlab/training/issues/34