Fix for https://github.com/instructlab/training/issues/254
instructlab/training pull request #273
Opened 2024-10-15 13:27 UTC by ashna000

Added checks for resolving the issue reported in https://github.com/instructlab/training/issues/254

2024-10-15 13:29 UTC, ashna000 commented
@RobotSail Can you please review this ?

2024-10-16 15:05 UTC, RobotSail commented on src/instructlab/training/multipack_sampler.py
> +        return len(dataset) / len(batches) if len(batches) > 0 else None
If we're hitting a scenario where Multipack generated no batches, then we need to either error out and have the calling function handle it (by falling back to `DistributedDataSampler`, or simply by preventing us from using multipack in the first place.

My recommendation here is to do this:
- Raise an appropriate exception here (either `RuntimeError` or `DivisionByZeroError`) 
- Have the calling function check for this additional exception and fall back to the naive sampler

2024-10-16 15:06 UTC, RobotSail commented
Thanks for this PR @ashna000, this will be a really important fix ! I've left a comment on how we should handle this problem.

2024-10-16 17:48 UTC, nathan-weinberg requested changes
@ashna000 can you please squash your commits?

2024-11-22 15:55 UTC, nathan-weinberg commented
@ashna000 these still need to be squashed

2025-01-31 04:03 UTC, closed without merging