Added some safeguards when the necessary imports are not available
instructlab/training pull request #291
Opened 2024-10-22 09:10 UTC by Harthi7

Context Issue:

https://github.com/instructlab/training/issues/250#issue-2570104902

Implemented error handling for the import of deepspeed to prevent runtime crashes
when the module is unavailable. This improves the robustness of the application.

Issue: https://github.com/instructlab/training/issues/250

2024-10-22 09:15 UTC, Harthi7 commented
Hey @RobotSail, I had rebasing/signing-off problem in my previous branch (https://github.com/instructlab/training/pull/267) so I made a new branch with the requested changes. Please let me know what you think

2024-10-23 12:59 UTC, RobotSail approved these changes
LGTM

2024-10-28 08:20 UTC, Harthi7 commented
Hello @Maxusmusti, This PR is ready for review please let me know what you think.

2024-10-29 04:22 UTC, Maxusmusti commented
@Harthi7 will take a look today, thanks!

2024-10-29 20:43 UTC, Maxusmusti requested changes

2024-10-29 20:43 UTC, Maxusmusti commented on src/instructlab/training/main_ds.py
> +    if args.distributed_training_framework == 'deeppeed' and args.cpu_offload_optimizer and not DeepSpeedCPUAdam:
@Harthi7 typo here, `deeppeed` -> `deepspeed`

2024-10-30 08:56 UTC, Harthi7 commented on src/instructlab/training/main_ds.py
> +    if args.distributed_training_framework == 'deeppeed' and args.cpu_offload_optimizer and not DeepSpeedCPUAdam:
Good catch, Fixed

2024-10-30 15:35 UTC, Maxusmusti commented
Looks like you are hitting some linting/formatting issues, but otherwise looks good

2024-11-03 09:14 UTC, Harthi7 commented
> Looks like you are hitting some linting/formatting issues, but otherwise looks good

Fixed, Please take a look and let me know what you think @Maxusmusti

2024-11-04 19:19 UTC, Maxusmusti commented
Re-triggering tests

2024-11-04 23:34 UTC, Maxusmusti commented
@Harthi7 looks like it is still failing linting and formatting, you can run the following to identify the linting issues and automatically reformat:
```
python3.11 -m tox p -e lint,mypy,ruff
```

2024-11-05 21:57 UTC, JamesKunstle commented
@Harthi7 this is a great addition, would you please fix the linting + minor issues?

2024-11-07 11:15 UTC, Harthi7 commented
I fixed the Pylint/Formatting issue, Please take a look again @Maxusmusti

2024-11-07 14:21 UTC, Maxusmusti commented
@JamesKunstle

2024-11-08 20:23 UTC, JamesKunstle commented on src/instructlab/training/main_ds.py
> +try:
You separated these try-except blocks because DeepSpeedCPUAdam is only imported for CPU offloading training correct? It'd be appreciated to have this documented since you're repeating code.

2024-11-08 20:23 UTC, JamesKunstle requested changes
Just wanting clarification on the import try-except with a comment, otherwise it'll be good to go in.

2024-11-08 21:53 UTC, Harthi7 commented on src/instructlab/training/main_ds.py
> +try:
Yes, I believe that is correct as @RobotSail have stated in a previous comment https://github.com/instructlab/training/pull/267#issuecomment-2426747170, as for the documentation how should we move forward?

2024-11-08 22:24 UTC, RobotSail commented on src/instructlab/training/main_ds.py
> +try:
Correct

2024-11-11 23:10 UTC, JamesKunstle approved these changes
Nice, this is really helpful. I appreciate your contribution!

2024-11-12 04:40 UTC, Maxusmusti approved these changes

2024-11-12 04:41 UTC, merged