feat: add log exporting to e2e tests
instructlab/training pull request #308
Opened 2024-10-25 22:08 UTC by RobotSail

Currently, the training library runs through a series of end-to-end tests which ensure there are
no bugs in the code being tested. However; we do not perform any form of validation to assure that
the training logic and quality has not diminished.

This presents an issue where we can potentially be "correct" in the sense of no hard errors being hit,
but invisible bugs may be introduced which cause models to regress in training quality, or other
bugs that plague the models themselves to seep in.

This commit fixes that problem by introducng the ability to export the training loss data itself
from the test and rendering the loss curve using matplotlib.

Signed-off-by: Oleg S <97077423+RobotSail@users.noreply.github.com>

2024-10-25 22:59 UTC, danmcp requested changes

2024-10-25 22:59 UTC, danmcp commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +
Was there a reason for adding the whitespace here and below?

2024-10-25 22:59 UTC, danmcp commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +            --bucket-name "${{ vars.AWS_S3_BUCKET_NAME }}" \
This variable name should probably be a little more specific to the task:

Ex: AWS_S3_LOSS_GRAPHS_BUCKET_NAME

2024-10-26 17:16 UTC, RobotSail commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +
Yeah, probably an artifact from when I pasted over my changes into this file

2024-10-26 17:17 UTC, RobotSail commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +
Will delete

2024-10-26 17:17 UTC, RobotSail commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +            --bucket-name "${{ vars.AWS_S3_BUCKET_NAME }}" \
Good point, I'll make that change

2024-10-26 17:26 UTC, RobotSail commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +            --bucket-name "${{ vars.AWS_S3_BUCKET_NAME }}" \
Done

2024-10-26 17:26 UTC, RobotSail commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +
Done

2024-10-26 17:45 UTC, danmcp commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +
Looks like there was one extra newline left here.  Was that one intentional?

2024-10-28 19:37 UTC, RobotSail commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +
No

2024-10-28 21:03 UTC, JamesKunstle approved these changes
lgtm!

2024-10-29 16:34 UTC, nathan-weinberg requested changes

2024-10-29 16:34 UTC, nathan-weinberg commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +          export PRESERVE=1
Where is this var used?

2024-10-29 16:34 UTC, nathan-weinberg commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +          # and we know that it will be written into a directory created by mktemp -d.
small readability nit
```suggestion
          # and we know that it will be written into a directory created by `mktemp -d`
```

2024-10-29 16:34 UTC, nathan-weinberg commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +        uses: actions/upload-artifact@v4
Can we use a hardened action here per the [org policy](https://github.com/instructlab/dev-docs/blob/main/docs/github-actions-use-policy.md#harden-the-github-action-runner)?

2024-10-29 16:34 UTC, nathan-weinberg commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +
Can you remove it?

2024-10-29 16:34 UTC, nathan-weinberg commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +        uses: actions/download-artifact@v4
Same comment on hardening here

2024-10-29 16:34 UTC, nathan-weinberg commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +      - name: Upload training logs
```suggestion
          mv "${log_file}" training-log.jsonl

      - name: Upload training logs
```

2024-10-29 16:34 UTC, nathan-weinberg commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +          pip install -r requirements-dev.txt
Aren't dependencies already installed further up?

2024-10-29 16:34 UTC, nathan-weinberg commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +      - name: Try to upload to s3
So this says `Try to upload to s3` - do we assume a chance of failure? What is the job behavior if this step succeeds versus if it fails?

2024-10-29 16:34 UTC, nathan-weinberg commented on .github/workflows/e2e-nvidia-l40s-x4.yml
> +          # and we know that it will be written into a directory created by mktemp -d.
Same comment as above

```suggestion
          # and we know that it will be written into a directory created by `mktemp -d`
```

2024-10-29 16:34 UTC, nathan-weinberg commented on .github/workflows/e2e-nvidia-l40s-x4.yml
> +          pip install -r requirements-dev.txt
Same comment as above

2024-10-29 16:34 UTC, nathan-weinberg commented on .github/workflows/e2e-nvidia-l40s-x4.yml
> +      - name: Try to upload to s3
Same comment as above

2024-10-31 03:52 UTC, RobotSail commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +          export PRESERVE=1
Inside of the e2e test script. It prevents the temp dir from being deleted.

2024-10-31 03:52 UTC, RobotSail commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +
Yes when I'm back from PTO

2024-10-31 14:46 UTC, nathan-weinberg commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +          export PRESERVE=1
Why not just use the flag?

2024-11-05 22:58 UTC, RobotSail commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +          export PRESERVE=1
@nathan-weinberg Could you please help me understand why we wouldn't want to use the env here? If we don't expect it to be used then we should just not have it in the script entirely.

2024-11-05 22:58 UTC, RobotSail commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +          # and we know that it will be written into a directory created by mktemp -d.
These little details are important so I'm glad you caught this.

2024-11-05 22:59 UTC, RobotSail commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +        uses: actions/upload-artifact@v4
Yes of course.

2024-11-05 23:06 UTC, RobotSail commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +        uses: actions/download-artifact@v4
Added it 🫡

2024-11-05 23:07 UTC, RobotSail commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +          pip install -r requirements-dev.txt
My understanding is that there are 3 jobs: 
- One to start the ec2 runner
- The ec2 runner
- One to stop the ec2 runner

Unless I'm mistaken, I believe this one has a separate scope to the ec2 runner, so it needs to install the dev deps again.

2024-11-05 23:10 UTC, RobotSail commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +      - name: Try to upload to s3
Should we fail the end-to-end run if we failed to upload to S3? If so, then we'd need to rerun the entire ec2 job. Else, we could succeed & provide a warning in the PR/summary that we could not upload to S3. 

There are two thoughts I'd have on this:
1. Testing for functional correctness is primary, loss correctness is secondary - here we consider the loss failing to upload as not a failure of the PR
2. Testing for loss + functional correctness is primary. Here we would hold a failure to upload to S3 with the same weight as themselves failing.

Let me know what your thoughts are on how we should proceed.

2024-11-05 23:20 UTC, RobotSail commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +
Done

2024-11-06 14:13 UTC, RobotSail commented on .github/workflows/e2e-nvidia-l40s-x4.yml
> +          pip install -r requirements-dev.txt
Answered in the other comment, basically isn't this running on another runner? In which case we'd need to reinstall dependencies.

2024-11-06 14:14 UTC, RobotSail commented on .github/workflows/e2e-nvidia-l40s-x4.yml
> +      - name: Try to upload to s3
Responded in the other thread - we need to decide whether failing to upload or not should null the results of an otherwise successful E2E run

2024-11-06 14:16 UTC, RobotSail commented on .github/workflows/e2e-nvidia-l40s-x4.yml
> +          # and we know that it will be written into a directory created by mktemp -d.
I made the change, thank you for paying attention to details like this. It makes our codebase more enjoyable to work on in the long-term.

2024-11-06 17:34 UTC, nathan-weinberg commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +          export PRESERVE=1
The flag just sets the env: https://github.com/instructlab/instructlab/blob/main/scripts/e2e-ci.sh#L433

I'm saying instead of setting it in the workflow file, just pass `-mp` instead of `-m`

2024-11-06 17:34 UTC, nathan-weinberg commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +        uses: actions/upload-artifact@v4
Thanks! Can you include the version number in a comment next to it like we do elsewhere?

2024-11-06 17:35 UTC, nathan-weinberg commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +      - name: Upload training logs
Was this done?

2024-11-06 17:36 UTC, nathan-weinberg commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +          pip install -r requirements-dev.txt
Oh I see, so the deps are being installed here not on the AWS runner but on the GitHub runner orchestrating the overall action here?

2024-11-06 17:37 UTC, nathan-weinberg commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +      - name: Try to upload to s3
Honestly I'm fine with either, up to you and the @instructlab/training-maintainers! My suggestion: we go for 1 but include something like this? https://stackoverflow.com/questions/74907704/is-there-a-github-actions-warning-state

2024-11-06 17:38 UTC, nathan-weinberg commented on .github/workflows/e2e-nvidia-l40s-x4.yml
> +          pip install -r requirements-dev.txt
Yeah let's have the convo in that thread so we don't trip over ourselves here :smile:

2024-11-06 17:38 UTC, nathan-weinberg commented on .github/workflows/e2e-nvidia-l40s-x4.yml
> +      - name: Try to upload to s3
Yup, same as the other let's just talk on that thread

2024-11-07 21:52 UTC, RobotSail commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +          pip install -r requirements-dev.txt
Yeah, the ec2 runner is only in charge of passing the log data back to the stop runner, but it does so through the use of github blobs (temporary GH S3-like storage).

2024-11-07 21:52 UTC, RobotSail commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +        uses: actions/upload-artifact@v4
Absolutely!

2024-11-07 21:53 UTC, RobotSail commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +          export PRESERVE=1
I see, that makes much more sense. I'll change it to use the flag then.

2024-11-08 17:00 UTC, nathan-weinberg commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +          pip install -r requirements-dev.txt
Gotcha, makes sense!

2024-11-13 14:45 UTC, RobotSail commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +      - name: Try to upload to s3
I've updated it to include this warning. Let me know if it lines up with what you expect.

2024-11-13 14:47 UTC, RobotSail commented
@nathan-weinberg I've updated the CI scripts with your feedback, please take another pass when you get a chance and make sure that we didn't miss anything.

2024-11-13 15:43 UTC, nathan-weinberg approved these changes
I'd like the version number commenting to be consistent with how is it everywhere else, but otherwise LGTM

2024-11-13 15:43 UTC, nathan-weinberg commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7
```suggestion
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
```

2024-11-13 15:43 UTC, nathan-weinberg commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7
```suggestion
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
```

2024-11-13 15:43 UTC, nathan-weinberg commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7
```suggestion
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
```

2024-11-13 17:30 UTC, RobotSail commented on .github/workflows/e2e-nvidia-l4-x1.yml
> +        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7
I can make this change, I like this a lot more.

2024-11-13 17:33 UTC, danmcp approved these changes

2024-11-13 19:26 UTC, RobotSail commented
@nathan-weinberg This has been squashed, I'll remove the hold since that's the only issue.

2024-11-13 21:13 UTC, merged