Beginning should be spelt correctly.
instructlab/training pull request #365
Opened 2024-12-11 21:37 UTC by jjasghar

It looks like `beginning` was spelt incorrectly.

/cc @nimbinatus

2024-12-16 20:17 UTC, JamesKunstle commented
Is `beginingoftext` correct or should it be `beginningoftext`

2024-12-17 21:47 UTC, nathan-weinberg commented
@Mergifyio rebase

2024-12-20 21:51 UTC, nimbinatus requested changes

2024-12-20 21:51 UTC, nimbinatus commented on src/instructlab/training/chat_templates/ibm_legacy_tmpl.py
> +    bos=TokenInfo("<|beginingoftext|>", add_to_tokenizer=True),
```suggestion
    bos=TokenInfo("<|beginningoftext|>", add_to_tokenizer=True),
```

2025-02-04 12:43 UTC, closed without merging